web:
  image: apparena/php7-xdebug
  ports:
    - "80:80"
  links:
    - mysql
  volumes:
    - .:/var/www/html
    - "./build/php.ini:/usr/local/etc/php/php.ini"
  env_file:
      - build/env

mysql:
  image: mysql:5.6.23
  ports:
      - "3306:3306"
    env_file:
    - build/env
